package sop_corba;


/**
* sop_corba/_ControladorCancionIntStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* viernes 5 de agosto de 2022 10:16:45 AM CDT
*/

public class _ControladorCancionIntStub extends org.omg.CORBA.portable.ObjectImpl implements sop_corba.ControladorCancionInt
{

  public boolean registrarCancion (sop_corba.ControladorCancionIntPackage.CancionDTO objCancion)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("registrarCancion", true);
                sop_corba.ControladorCancionIntPackage.CancionDTOHelper.write ($out, objCancion);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return registrarCancion (objCancion        );
            } finally {
                _releaseReply ($in);
            }
  } // registrarCancion

  public sop_corba.ControladorCancionIntPackage.CancionDTO[] listarCanciones ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("listarCanciones", true);
                $in = _invoke ($out);
                sop_corba.ControladorCancionIntPackage.CancionDTO $result[] = sop_corba.ControladorCancionIntPackage.ListCancionesHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return listarCanciones (        );
            } finally {
                _releaseReply ($in);
            }
  } // listarCanciones

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:sop_corba/ControladorCancionInt:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _ControladorCancionIntStub
