package sop_corba;


/**
* sop_corba/ControladorCancionInt.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* viernes 5 de agosto de 2022 10:16:45 AM CDT
*/

public interface ControladorCancionInt extends ControladorCancionIntOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ControladorCancionInt
