package sop_corba.ControladorCancionIntPackage;


/**
* sop_corba/ControladorCancionIntPackage/CancionDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* viernes 5 de agosto de 2022 10:16:46 AM CDT
*/

public final class CancionDTO implements org.omg.CORBA.portable.IDLEntity
{
  public int id = (int)0;
  public String artista = null;
  public String titulo = null;
  public int tamKB = (int)0;
  public byte audio[] = null;

  public CancionDTO ()
  {
  } // ctor

  public CancionDTO (int _id, String _artista, String _titulo, int _tamKB, byte[] _audio)
  {
    id = _id;
    artista = _artista;
    titulo = _titulo;
    tamKB = _tamKB;
    audio = _audio;
  } // ctor

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getArtista() {
        return artista;
    }

    public void setArtista(String artista) {
        this.artista = artista;
    }

    public String getTitulo() {
        return titulo;
    }

    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    public int getTamKB() {
        return tamKB;
    }

    public void setTamKB(int tamKB) {
        this.tamKB = tamKB;
    }

    public byte[] getAudio() {
        return audio;
    }

    public void setAudio(byte[] audio) {
        this.audio = audio;
    }
  
  

} // class CancionDTO
